version: '3.8'

services:
  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://demodb1.cxeeucco4xnb.ap-south-1.rds.amazonaws.com:5432/demodb1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root12345678