name: Spring Boot CI

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: ./mvnw test

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t springboot-crud:${{ github.sha }} .